# Generated by Django 6.1.1 on 2026-09-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stoke',
            new_name='stock',
        ),
    ]
